preload=/home/gfe/Personal/dionysus/dotfiles/hypr/wallpapers/laptop-wallpaper.webp
wallpaper=eDP-1,/home/gfe/Personal/dionysus/dotfiles/hypr/wallpapers/laptop-wallpaper.webp
wallpaper=HDMI-A-1,/home/gfe/Personal/dionysus/dotfiles/hypr/wallpapers/laptop-wallpaper.webp
fit=1
