preload=/home/gfe/Pictures/how-did-pewdiepie-get-his-waybar-looking-like-this-v0-3vgzbhbnxyze1.webp
wallpaper=eDP-1,/home/gfe/Pictures/how-did-pewdiepie-get-his-waybar-looking-like-this-v0-3vgzbhbnxyze1.webp
wallpaper=HDMI-A-1,/home/gfe/Pictures/how-did-pewdiepie-get-his-waybar-looking-like-this-v0-3vgzbhbnxyze1.webp
fit=1
